unit UUseMode;

interface

uses
  Winapi.Windows,
  Winapi.Messages,
  System.SysUtils,
  System.Variants,
  System.Classes,
  Vcl.Graphics,
  Vcl.Controls,
  Vcl.Forms,
  Vcl.Dialogs,
  Vcl.StdCtrls,
  Vcl.ExtCtrls,
  Vcl.Mask,
  Data.DB,
  Datasnap.DBClient,
  Vcl.Grids,
  Vcl.DBGrids,
  RRClass,
  UTips;

type
  TfUseMode = class(TfObject)
    ColorBox1: TColorBox;
    Button2: TButton;
    DBGrid1: TDBGrid;
    Label8: TLabel;
    ClientDataSet1: TClientDataSet;
    ClientDataSet1id: TAutoIncField;
    ClientDataSet1nome: TStringField;
    ClientDataSet1idade: TIntegerField;
    DataSource1: TDataSource;
    GroupBox1: TGroupBox;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    lbStatus: TLabel;
    LabeledEdit3: TLabeledEdit;
    LabeledEdit4: TLabeledEdit;
    Button1: TButton;
    ComboBox1: TComboBox;
    MaskEdit1: TMaskEdit;
    MaskEdit2: TMaskEdit;
    MaskEdit3: TMaskEdit;
    MaskEdit4: TMaskEdit;
    MaskEdit5: TMaskEdit;
    MaskEdit6: TMaskEdit;
    RadioGroup1: TRadioGroup;
    RadioGroup2: TRadioGroup;
    ColorBox2: TColorBox;
    Label9: TLabel;
    Button3: TButton;
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure RadioGroup1Click(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure Button3Click(Sender: TObject);
  protected
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fUseMode: TfUseMode;

implementation

{$R *.dfm}

procedure TfUseMode.Button1Click(Sender: TObject);
var
  //oDef: IFDStanConnectionDef;
  ListIgnora : TStringList;
  TreatType : TTreatFormType;
begin
  ListIgnora := TStringList.Create;
  ListIgnora.Add(LabeledEdit4.Name);
  ListIgnora.Add(RadioGroup1.Name);
  ListIgnora.Add(ColorBox1.Name);

  case RadioGroup2.ItemIndex of
    0 : TreatType := TTreatFormType.ttDefault;
    1 : TreatType := TTreatFormType.ttBalloonTipInOne;
    2 : TreatType := TTreatFormType.ttBalloonTipInAll;
    3 : TreatType := TTreatFormType.ttPaintControlInOne;
    4 : TreatType := TTreatFormType.ttPaintControlInAll;
  end;

  if StartTreatment(ListIgnora, TreatType) then
    lbStatus.Caption := 'OK'
  else
    lbStatus.Caption := 'Não OK';

  ListIgnora.Free;
end;

procedure TfUseMode.Button2Click(Sender: TObject);
begin
  DBGrid1.ColorDataCell := ColorBox1.Selected;
end;

procedure TfUseMode.Button3Click(Sender: TObject);
begin
  ColorBox2.SetBorder(Colorbox2.Selected);
end;

procedure TfUseMode.FormCreate(Sender: TObject);
begin
  Inherited;
  ClientDataSet1.CreateDataSet;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;

  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Ramon Ruan';
  ClientDataSet1idade.asinteger := 25;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste1';
  ClientDataSet1idade.asinteger := 15;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Teste2';
  ClientDataSet1idade.asinteger := 14;
  ClientDataSet1.Post;
  ClientDataSet1.Insert;
  ClientDataSet1nome.AsString := 'Hawina Nowell';
  ClientDataSet1idade.asinteger := 23;
  ClientDataSet1.Post;
end;

procedure TfUseMode.RadioGroup1Click(Sender: TObject);
begin
  case RadioGroup1.ItemIndex of
    0 : RadioGroup1.ShowBalloonTip(TIconKind.Info, 'Teste!', 'Teste de mensagem!');
    1 : RadioGroup1.ShowBalloonTip(TIconKind.Info_Large, 'Teste!', 'Teste de mensagem!');
    2 : RadioGroup1.ShowBalloonTip(TIconKind.Warning, 'Teste!', 'Teste de mensagem!');
    3 : RadioGroup1.ShowBalloonTip(TIconKind.Warning_Large, 'Teste!', 'Teste de mensagem!');
    4 : RadioGroup1.ShowBalloonTip(TIconKind.Error, 'Teste!', 'Teste de mensagem!');
    5 : RadioGroup1.ShowBalloonTip(TIconKind.Eror_Large, 'Teste!', 'Teste de mensagem!');
    6 : RadioGroup1.ShowBalloonTip(TIconKind.None, 'Teste!', 'Teste de mensagem!');
  end;
end;

end.
